INSERT INTO condominios VALUES (1, 'Terra Nova');
INSERT INTO condominios VALUES (2, 'Jardim America');

INSERT INTO grupos VALUES (3, 'Morador', 1);
INSERT INTO grupos VALUES (4, 'Sindico', 1);
INSERT INTO grupos VALUES (5, 'Porteiro',1);
INSERT INTO grupos VALUES (6, 'Morador', 2);
INSERT INTO grupos VALUES (7, 'Sindico', 2);
INSERT INTO grupos VALUES (8, 'Porteiro', 2);

INSERT INTO permissoes VALUES (9, 'Usuarios', 'Escrita');
INSERT INTO permissoes VALUES (10, 'Usuarios', 'Leitura');
INSERT INTO permissoes VALUES (11, 'Usuarios', 'Nenhuma');
INSERT INTO permissoes VALUES (12, 'Reservas', 'Escrita');
INSERT INTO permissoes VALUES (13, 'Reservas', 'Leitura');
INSERT INTO permissoes VALUES (14, 'Reservas', 'Nenhuma');
INSERT INTO permissoes VALUES (15, 'Entregas', 'Escrita');
INSERT INTO permissoes VALUES (16, 'Entregas', 'Leitura');
INSERT INTO permissoes VALUES (17, 'Entregas', 'Nenhuma');

INSERT INTO grupos_permissoes VALUES (3, 10);
INSERT INTO grupos_permissoes VALUES (3, 12);
INSERT INTO grupos_permissoes VALUES (3, 17);
INSERT INTO grupos_permissoes VALUES (4, 9);
INSERT INTO grupos_permissoes VALUES (4, 13);
INSERT INTO grupos_permissoes VALUES (4, 17);
INSERT INTO grupos_permissoes VALUES (5, 10);
INSERT INTO grupos_permissoes VALUES (5, 12);
INSERT INTO grupos_permissoes VALUES (5, 15);
INSERT INTO grupos_permissoes VALUES (6, 10);
INSERT INTO grupos_permissoes VALUES (6, 12);
INSERT INTO grupos_permissoes VALUES (6, 17);
INSERT INTO grupos_permissoes VALUES (7, 9);
INSERT INTO grupos_permissoes VALUES (7, 12);
INSERT INTO grupos_permissoes VALUES (7, 16);
INSERT INTO grupos_permissoes VALUES (8, 10);
INSERT INTO grupos_permissoes VALUES (8, 13);
INSERT INTO grupos_permissoes VALUES (8, 15);

INSERT INTO usuarios VALUES (18, true, '123', 'alencar.amorin@gmail.com');
INSERT INTO usuarios VALUES (19, true, '123', 'pedro.lopez@gmail.com');
INSERT INTO usuarios VALUES (20, true, '123', 'eduarda.carvalho.sindica@gmail.com');
INSERT INTO usuarios VALUES (21, true, '123', 'mauricio.oliveira@gmail.com');
INSERT INTO usuarios VALUES (22, true, '123', 'rafaela.rodriguez@gmail.com');
INSERT INTO usuarios VALUES (23, true, '123', 'tiago.trindade@gmail.com');
INSERT INTO usuarios VALUES (24, true, '123', 'felipe.oliveira@gmail.com');
INSERT INTO usuarios VALUES (25, true, '123', 'gabriela.silveira@gmail.com');
INSERT INTO usuarios VALUES (26, true, '123', 'henrique.menezes@gmail.com');
INSERT INTO usuarios VALUES (27, true, '123', 'joao.silva@gmail.com');
INSERT INTO usuarios VALUES (28, true, '123', 'leandro.braga@gmail.com');
INSERT INTO usuarios VALUES (29, true, '123', 'leonardo.lima@gmail.com');
INSERT INTO usuarios VALUES (30, true, '123', 'marcia.soares@gmail.com');
INSERT INTO usuarios VALUES (31, true, '123', 'marcos.fraga@gmail.com');

INSERT INTO usuarios_grupos VALUES (18, 3);
INSERT INTO usuarios_grupos VALUES (19, 6);
INSERT INTO usuarios_grupos VALUES (20, 3);
INSERT INTO usuarios_grupos VALUES (20, 4);
INSERT INTO usuarios_grupos VALUES (21, 3);
INSERT INTO usuarios_grupos VALUES (22, 6);
INSERT INTO usuarios_grupos VALUES (23, 6);
INSERT INTO usuarios_grupos VALUES (24, 3);
INSERT INTO usuarios_grupos VALUES (24, 4);
INSERT INTO usuarios_grupos VALUES (24, 7);
INSERT INTO usuarios_grupos VALUES (25, 3);
INSERT INTO usuarios_grupos VALUES (26, 8);
INSERT INTO usuarios_grupos VALUES (27, 6);
INSERT INTO usuarios_grupos VALUES (28, 6);
INSERT INTO usuarios_grupos VALUES (29, 3);
INSERT INTO usuarios_grupos VALUES (29, 6);
INSERT INTO usuarios_grupos VALUES (30, 3);
INSERT INTO usuarios_grupos VALUES (31, 3);